name: todo-app

services:
  mongo:
    image: mongo:7.0.12
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - todo-app

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - todo-app
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - todo-app
    ports:
      - "5173:5173"  
    command: npm run dev -- --host 
    depends_on:
      - api

volumes:
  mongo_data:

networks:
  todo-app:
    driver: bridge
